version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: learningByDoing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  spring-boot-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/learningByDoing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/learningByDoing_db

    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - mongo

#  angular-app:
#    build: ./angular-app
#    ports:
#      - "80:80"

volumes:
  postgres_data:
  mongo_data:
