
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: learningByDoing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp/backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/learningByDoing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ppt_cours
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:
