name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build backend image
        run: docker build -t najouaelhabti/learningbydoing-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t najouaelhabti/learningbydoing-frontend:latest ./frontend

      - name: Push backend image
        run: docker push najouaelhabti/learningbydoing-backend:latest

      - name: Push frontend image
        run: docker push najouaelhabti/learningbydoing-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.20.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          # Debugging
          ls -la /usr/local/bin/docker-compose
          file /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy services
        run: |
          docker-compose -f docker-compose.yml up -d
