name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build backend image
        run: docker build -t learningbydoing/backend:latest ./backend

      - name: Build frontend image
        run: docker build -t learningbydoing/frontend:latest ./frontend

      - name: Push backend image
        run: docker push learningbydoing/backend:latest

      - name: Push frontend image
        run: docker push learningbydoing/frontend:latest

      - name: Deploy services (Optional)
        run: |
          docker-compose up -d
