name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker and Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # Build and run all services with docker-compose
      - name: Build and run services
        run: docker-compose up --build -d

      # Wait for services to be healthy (you can customize this if needed)
      - name: Wait for backend to be ready
        run: |
          docker-compose exec -T spring-boot-app sh -c 'while ! nc -z localhost 8080; do sleep 1; done'

      # Run backend tests
      - name: Run backend tests
        run: docker-compose exec spring-boot-app ./mvnw test
        working-directory: backend

      # Run frontend tests
      - name: Run frontend tests
        run: docker-compose exec angular-app npm test -- --watch=false
        working-directory: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Push backend Docker image
      - name: Push backend Docker image
        run: docker push najouaelhabti/backend:latest

      # Push frontend Docker image
      - name: Push frontend Docker image
        run: docker push najouaelhabti/frontend:latest

